# Generated by Django 4.1 on 2022-08-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='summmary',
            new_name='summary',
        ),
    ]
